/*
  Migration: create_user_profile_and_biblia.sql
  Description: Creates the user_profile and biblia tables for per‑user data and Bible verse storage.
*/

CREATE TABLE IF NOT EXISTS public.user_profile (
  email TEXT PRIMARY KEY,
  theme TEXT DEFAULT 'light',
  reminder_enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.biblia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT REFERENCES public.user_profile(email) ON DELETE CASCADE,
  book TEXT NOT NULL,
  chapter INT NOT NULL,
  verse INT NOT NULL,
  content TEXT NOT NULL,
  version TEXT,
  added_at TIMESTAMPTZ DEFAULT now()
);
